# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dzhua.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dzhua.proto',
  package='dzhyun',
  syntax='proto2',
  serialized_pb=_b('\n\x0b\x64zhua.proto\x12\x06\x64zhyun\"E\n\nUAResponse\x12\x0b\n\x03Qid\x18\x01 \x02(\t\x12\x0b\n\x03\x45rr\x18\x02 \x02(\x05\x12\x0f\n\x07\x43ounter\x18\x03 \x02(\r\x12\x0c\n\x04\x44\x61ta\x18\x04 \x01(\x0c\")\n\rChildResponse\x12\n\n\x02No\x18\x01 \x02(\x05\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\x0c\"8\n\rGroupResponse\x12\'\n\x08\x43hildRes\x18\x01 \x03(\x0b\x32\x15.dzhyun.ChildResponseB\x12\n\x10\x63om.dzhyun.proto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UARESPONSE = _descriptor.Descriptor(
  name='UAResponse',
  full_name='dzhyun.UAResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Qid', full_name='dzhyun.UAResponse.Qid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Err', full_name='dzhyun.UAResponse.Err', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Counter', full_name='dzhyun.UAResponse.Counter', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Data', full_name='dzhyun.UAResponse.Data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=92,
)


_CHILDRESPONSE = _descriptor.Descriptor(
  name='ChildResponse',
  full_name='dzhyun.ChildResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='No', full_name='dzhyun.ChildResponse.No', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Data', full_name='dzhyun.ChildResponse.Data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=135,
)


_GROUPRESPONSE = _descriptor.Descriptor(
  name='GroupResponse',
  full_name='dzhyun.GroupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChildRes', full_name='dzhyun.GroupResponse.ChildRes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=193,
)

_GROUPRESPONSE.fields_by_name['ChildRes'].message_type = _CHILDRESPONSE
DESCRIPTOR.message_types_by_name['UAResponse'] = _UARESPONSE
DESCRIPTOR.message_types_by_name['ChildResponse'] = _CHILDRESPONSE
DESCRIPTOR.message_types_by_name['GroupResponse'] = _GROUPRESPONSE

UAResponse = _reflection.GeneratedProtocolMessageType('UAResponse', (_message.Message,), dict(
  DESCRIPTOR = _UARESPONSE,
  __module__ = 'dzhua_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.UAResponse)
  ))
_sym_db.RegisterMessage(UAResponse)

ChildResponse = _reflection.GeneratedProtocolMessageType('ChildResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHILDRESPONSE,
  __module__ = 'dzhua_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.ChildResponse)
  ))
_sym_db.RegisterMessage(ChildResponse)

GroupResponse = _reflection.GeneratedProtocolMessageType('GroupResponse', (_message.Message,), dict(
  DESCRIPTOR = _GROUPRESPONSE,
  __module__ = 'dzhua_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.GroupResponse)
  ))
_sym_db.RegisterMessage(GroupResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020com.dzhyun.proto'))
# @@protoc_insertion_point(module_scope)
