# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dzhyun.blockstatistics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dzhyun.blockstatistics.proto',
  package='dzhyun',
  syntax='proto2',
  serialized_pb=_b('\n\x1c\x64zhyun.blockstatistics.proto\x12\x06\x64zhyun\"\x86\x06\n\tTongJiApp\x12\x12\n\nChengJiaoE\x18\x01 \x01(\x03\x12\x15\n\rLiuTongShiZhi\x18\x02 \x01(\x03\x12\x12\n\nZongShiZhi\x18\x03 \x01(\x03\x12\x39\n\x0cZhangDiePing\x18\x04 \x01(\x0b\x32#.dzhyun.TongJiApp.ZhangDiePingShuJu\x12\x37\n\x0bLingZhangGu\x18\x05 \x01(\x0b\x32\".dzhyun.TongJiApp.LingZhangGuShuJu\x12\x15\n\rTingPaiJiaShu\x18\x06 \x01(\x03\x12\x41\n\x10ZhangTingDieTing\x18\x07 \x01(\x0b\x32\'.dzhyun.TongJiApp.ZhangTingDieTingShuJu\x12\x13\n\x0bGuPiaoGeShu\x18\x08 \x01(\x03\x12\x1f\n\x17PingJunJingTaiShiYingLv\x18\t \x01(\x03\x12\x12\n\nZiJinJingE\x18\n \x01(\x03\x12;\n\rZiJinLiuXiang\x18\x0b \x03(\x0b\x32$.dzhyun.TongJiApp.ZiJinLiuXiangShuJu\x12\x0e\n\x06JunJia\x18\x0c \x01(\x03\x12\x15\n\rJiaQuanJunJia\x18\r \x01(\x03\x1a^\n\x10LingZhangGuShuJu\x12\x0b\n\x03Obj\x18\x01 \x02(\t\x12\x19\n\x11ZhongWenJianCheng\x18\x02 \x01(\t\x12\x11\n\tZuiXinJia\x18\x03 \x01(\x03\x12\x0f\n\x07ZhangFu\x18\x04 \x01(\x03\x1aZ\n\x11ZhangDiePingShuJu\x12\x18\n\x10ShangZhangJiaShu\x18\x01 \x01(\x03\x12\x14\n\x0cXiaDieJiaShu\x18\x02 \x01(\x03\x12\x15\n\rPingPanJiaShu\x18\x03 \x01(\x03\x1aG\n\x15ZhangTingDieTingShuJu\x12\x17\n\x0fZhangTingJiaShu\x18\x01 \x01(\x03\x12\x15\n\rDieTingJiaShu\x18\x02 \x01(\x03\x1a\x39\n\x12ZiJinLiuXiangShuJu\x12\x0f\n\x07ShiJian\x18\x01 \x01(\x03\x12\x12\n\nZiJinJingE\x18\x02 \x01(\x03\x42\x12\n\x10\x63om.dzhyun.proto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TONGJIAPP_LINGZHANGGUSHUJU = _descriptor.Descriptor(
  name='LingZhangGuShuJu',
  full_name='dzhyun.TongJiApp.LingZhangGuShuJu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Obj', full_name='dzhyun.TongJiApp.LingZhangGuShuJu.Obj', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZhongWenJianCheng', full_name='dzhyun.TongJiApp.LingZhangGuShuJu.ZhongWenJianCheng', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZuiXinJia', full_name='dzhyun.TongJiApp.LingZhangGuShuJu.ZuiXinJia', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZhangFu', full_name='dzhyun.TongJiApp.LingZhangGuShuJu.ZhangFu', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=591,
)

_TONGJIAPP_ZHANGDIEPINGSHUJU = _descriptor.Descriptor(
  name='ZhangDiePingShuJu',
  full_name='dzhyun.TongJiApp.ZhangDiePingShuJu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ShangZhangJiaShu', full_name='dzhyun.TongJiApp.ZhangDiePingShuJu.ShangZhangJiaShu', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='XiaDieJiaShu', full_name='dzhyun.TongJiApp.ZhangDiePingShuJu.XiaDieJiaShu', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PingPanJiaShu', full_name='dzhyun.TongJiApp.ZhangDiePingShuJu.PingPanJiaShu', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=683,
)

_TONGJIAPP_ZHANGTINGDIETINGSHUJU = _descriptor.Descriptor(
  name='ZhangTingDieTingShuJu',
  full_name='dzhyun.TongJiApp.ZhangTingDieTingShuJu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ZhangTingJiaShu', full_name='dzhyun.TongJiApp.ZhangTingDieTingShuJu.ZhangTingJiaShu', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DieTingJiaShu', full_name='dzhyun.TongJiApp.ZhangTingDieTingShuJu.DieTingJiaShu', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=756,
)

_TONGJIAPP_ZIJINLIUXIANGSHUJU = _descriptor.Descriptor(
  name='ZiJinLiuXiangShuJu',
  full_name='dzhyun.TongJiApp.ZiJinLiuXiangShuJu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ShiJian', full_name='dzhyun.TongJiApp.ZiJinLiuXiangShuJu.ShiJian', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZiJinJingE', full_name='dzhyun.TongJiApp.ZiJinLiuXiangShuJu.ZiJinJingE', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=758,
  serialized_end=815,
)

_TONGJIAPP = _descriptor.Descriptor(
  name='TongJiApp',
  full_name='dzhyun.TongJiApp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChengJiaoE', full_name='dzhyun.TongJiApp.ChengJiaoE', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LiuTongShiZhi', full_name='dzhyun.TongJiApp.LiuTongShiZhi', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZongShiZhi', full_name='dzhyun.TongJiApp.ZongShiZhi', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZhangDiePing', full_name='dzhyun.TongJiApp.ZhangDiePing', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LingZhangGu', full_name='dzhyun.TongJiApp.LingZhangGu', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TingPaiJiaShu', full_name='dzhyun.TongJiApp.TingPaiJiaShu', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZhangTingDieTing', full_name='dzhyun.TongJiApp.ZhangTingDieTing', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GuPiaoGeShu', full_name='dzhyun.TongJiApp.GuPiaoGeShu', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PingJunJingTaiShiYingLv', full_name='dzhyun.TongJiApp.PingJunJingTaiShiYingLv', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZiJinJingE', full_name='dzhyun.TongJiApp.ZiJinJingE', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZiJinLiuXiang', full_name='dzhyun.TongJiApp.ZiJinLiuXiang', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='JunJia', full_name='dzhyun.TongJiApp.JunJia', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='JiaQuanJunJia', full_name='dzhyun.TongJiApp.JiaQuanJunJia', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TONGJIAPP_LINGZHANGGUSHUJU, _TONGJIAPP_ZHANGDIEPINGSHUJU, _TONGJIAPP_ZHANGTINGDIETINGSHUJU, _TONGJIAPP_ZIJINLIUXIANGSHUJU, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=815,
)

_TONGJIAPP_LINGZHANGGUSHUJU.containing_type = _TONGJIAPP
_TONGJIAPP_ZHANGDIEPINGSHUJU.containing_type = _TONGJIAPP
_TONGJIAPP_ZHANGTINGDIETINGSHUJU.containing_type = _TONGJIAPP
_TONGJIAPP_ZIJINLIUXIANGSHUJU.containing_type = _TONGJIAPP
_TONGJIAPP.fields_by_name['ZhangDiePing'].message_type = _TONGJIAPP_ZHANGDIEPINGSHUJU
_TONGJIAPP.fields_by_name['LingZhangGu'].message_type = _TONGJIAPP_LINGZHANGGUSHUJU
_TONGJIAPP.fields_by_name['ZhangTingDieTing'].message_type = _TONGJIAPP_ZHANGTINGDIETINGSHUJU
_TONGJIAPP.fields_by_name['ZiJinLiuXiang'].message_type = _TONGJIAPP_ZIJINLIUXIANGSHUJU
DESCRIPTOR.message_types_by_name['TongJiApp'] = _TONGJIAPP

TongJiApp = _reflection.GeneratedProtocolMessageType('TongJiApp', (_message.Message,), dict(

  LingZhangGuShuJu = _reflection.GeneratedProtocolMessageType('LingZhangGuShuJu', (_message.Message,), dict(
    DESCRIPTOR = _TONGJIAPP_LINGZHANGGUSHUJU,
    __module__ = 'dzhyun.blockstatistics_pb2'
    # @@protoc_insertion_point(class_scope:dzhyun.TongJiApp.LingZhangGuShuJu)
    ))
  ,

  ZhangDiePingShuJu = _reflection.GeneratedProtocolMessageType('ZhangDiePingShuJu', (_message.Message,), dict(
    DESCRIPTOR = _TONGJIAPP_ZHANGDIEPINGSHUJU,
    __module__ = 'dzhyun.blockstatistics_pb2'
    # @@protoc_insertion_point(class_scope:dzhyun.TongJiApp.ZhangDiePingShuJu)
    ))
  ,

  ZhangTingDieTingShuJu = _reflection.GeneratedProtocolMessageType('ZhangTingDieTingShuJu', (_message.Message,), dict(
    DESCRIPTOR = _TONGJIAPP_ZHANGTINGDIETINGSHUJU,
    __module__ = 'dzhyun.blockstatistics_pb2'
    # @@protoc_insertion_point(class_scope:dzhyun.TongJiApp.ZhangTingDieTingShuJu)
    ))
  ,

  ZiJinLiuXiangShuJu = _reflection.GeneratedProtocolMessageType('ZiJinLiuXiangShuJu', (_message.Message,), dict(
    DESCRIPTOR = _TONGJIAPP_ZIJINLIUXIANGSHUJU,
    __module__ = 'dzhyun.blockstatistics_pb2'
    # @@protoc_insertion_point(class_scope:dzhyun.TongJiApp.ZiJinLiuXiangShuJu)
    ))
  ,
  DESCRIPTOR = _TONGJIAPP,
  __module__ = 'dzhyun.blockstatistics_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.TongJiApp)
  ))
_sym_db.RegisterMessage(TongJiApp)
_sym_db.RegisterMessage(TongJiApp.LingZhangGuShuJu)
_sym_db.RegisterMessage(TongJiApp.ZhangDiePingShuJu)
_sym_db.RegisterMessage(TongJiApp.ZhangTingDieTingShuJu)
_sym_db.RegisterMessage(TongJiApp.ZiJinLiuXiangShuJu)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020com.dzhyun.proto'))
# @@protoc_insertion_point(module_scope)
