# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dzhyun.historytrends.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dzhyun import topicinvest_pb2 as dzhyun_dot_topicinvest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dzhyun.historytrends.proto',
  package='dzhyun',
  syntax='proto2',
  serialized_pb=_b('\n\x1a\x64zhyun.historytrends.proto\x12\x06\x64zhyun\x1a\x18\x64zhyun.topicinvest.proto\".\n\rYueKXianShuJu\x12\x0c\n\x04Nian\x18\x01 \x02(\x03\x12\x0f\n\x07ZhangFu\x18\x02 \x01(\x03\"w\n\x0eYueZouShiShuJu\x12\x0b\n\x03Yue\x18\x01 \x02(\x03\x12\'\n\x08YueKXian\x18\x02 \x03(\x0b\x32\x15.dzhyun.YueKXianShuJu\x12\x17\n\x0fShangZhangGaiLv\x18\x03 \x01(\x03\x12\x16\n\x0ePingJunZhangFu\x18\x04 \x01(\x03\"G\n\rHistoryTrends\x12\x0b\n\x03Obj\x18\x01 \x02(\t\x12)\n\tYueZouShi\x18\x02 \x03(\x0b\x32\x16.dzhyun.YueZouShiShuJu\"C\n\x0bMonthTrends\x12\x0b\n\x03Obj\x18\x01 \x02(\t\x12\'\n\x08HangQing\x18\x02 \x03(\x0b\x32\x15.dzhyun.LiShiHangQingB\x12\n\x10\x63om.dzhyun.proto')
  ,
  dependencies=[dzhyun_dot_topicinvest__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_YUEKXIANSHUJU = _descriptor.Descriptor(
  name='YueKXianShuJu',
  full_name='dzhyun.YueKXianShuJu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Nian', full_name='dzhyun.YueKXianShuJu.Nian', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ZhangFu', full_name='dzhyun.YueKXianShuJu.ZhangFu', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=110,
)


_YUEZOUSHISHUJU = _descriptor.Descriptor(
  name='YueZouShiShuJu',
  full_name='dzhyun.YueZouShiShuJu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Yue', full_name='dzhyun.YueZouShiShuJu.Yue', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='YueKXian', full_name='dzhyun.YueZouShiShuJu.YueKXian', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ShangZhangGaiLv', full_name='dzhyun.YueZouShiShuJu.ShangZhangGaiLv', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PingJunZhangFu', full_name='dzhyun.YueZouShiShuJu.PingJunZhangFu', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=231,
)


_HISTORYTRENDS = _descriptor.Descriptor(
  name='HistoryTrends',
  full_name='dzhyun.HistoryTrends',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Obj', full_name='dzhyun.HistoryTrends.Obj', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='YueZouShi', full_name='dzhyun.HistoryTrends.YueZouShi', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=304,
)


_MONTHTRENDS = _descriptor.Descriptor(
  name='MonthTrends',
  full_name='dzhyun.MonthTrends',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Obj', full_name='dzhyun.MonthTrends.Obj', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HangQing', full_name='dzhyun.MonthTrends.HangQing', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=373,
)

_YUEZOUSHISHUJU.fields_by_name['YueKXian'].message_type = _YUEKXIANSHUJU
_HISTORYTRENDS.fields_by_name['YueZouShi'].message_type = _YUEZOUSHISHUJU
_MONTHTRENDS.fields_by_name['HangQing'].message_type = dzhyun_dot_topicinvest__pb2._LISHIHANGQING
DESCRIPTOR.message_types_by_name['YueKXianShuJu'] = _YUEKXIANSHUJU
DESCRIPTOR.message_types_by_name['YueZouShiShuJu'] = _YUEZOUSHISHUJU
DESCRIPTOR.message_types_by_name['HistoryTrends'] = _HISTORYTRENDS
DESCRIPTOR.message_types_by_name['MonthTrends'] = _MONTHTRENDS

YueKXianShuJu = _reflection.GeneratedProtocolMessageType('YueKXianShuJu', (_message.Message,), dict(
  DESCRIPTOR = _YUEKXIANSHUJU,
  __module__ = 'dzhyun.historytrends_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.YueKXianShuJu)
  ))
_sym_db.RegisterMessage(YueKXianShuJu)

YueZouShiShuJu = _reflection.GeneratedProtocolMessageType('YueZouShiShuJu', (_message.Message,), dict(
  DESCRIPTOR = _YUEZOUSHISHUJU,
  __module__ = 'dzhyun.historytrends_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.YueZouShiShuJu)
  ))
_sym_db.RegisterMessage(YueZouShiShuJu)

HistoryTrends = _reflection.GeneratedProtocolMessageType('HistoryTrends', (_message.Message,), dict(
  DESCRIPTOR = _HISTORYTRENDS,
  __module__ = 'dzhyun.historytrends_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.HistoryTrends)
  ))
_sym_db.RegisterMessage(HistoryTrends)

MonthTrends = _reflection.GeneratedProtocolMessageType('MonthTrends', (_message.Message,), dict(
  DESCRIPTOR = _MONTHTRENDS,
  __module__ = 'dzhyun.historytrends_pb2'
  # @@protoc_insertion_point(class_scope:dzhyun.MonthTrends)
  ))
_sym_db.RegisterMessage(MonthTrends)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020com.dzhyun.proto'))
# @@protoc_insertion_point(module_scope)
